"""add user profile

Revision ID: 6b07fa9daa25
Revises: 51f5ccfba190
Create Date: 2018-05-22 14:57:30.722284

"""

# revision identifiers, used by Alembic.
revision = '6b07fa9daa25'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
